version: "3.5"
services:
  app:
    container_name: sandol-notice-notification-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sandol-notice-notification/server:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
    networks:
      - sandol-network
    depends_on:
      amqp:
        condition: service_healthy
      db:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/notice-notification/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  db:
    container_name: sandol-notice-notification-db
    image: postgres:15
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5434:5432"
    volumes:
      - ./db_data_dev:/var/lib/postgresql/data
    networks:
      - sandol-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  amqp:
    container_name: amqp
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sandol-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sandol-network:
    driver: bridge

volumes:
  db_data:
