services:
  app:
    container_name: sandol-notice-notification-app
    build:
      context: .
      dockerfile: Dockerfile.dev

    restart: always
    env_file:
      - .env.dev
      - sandol_amqp/.env.amqp
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    networks:
      - sandol-network
    depends_on:
      amqp:
        condition: service_healthy
      db:
        condition: service_healthy

  db:
    container_name: sandol-notice-notification-db
    image: postgres:15
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sandol-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

networks:
  sandol-network:
    driver: bridge

volumes:
  db_data:
