version: "3.5"
services:
  app:
    container_name: sandol-notice-notification-app
    build:
      context: .
      dockerfile: Dockerfile
    image: sandol-notice-notification/server:latest
    restart: always
    env_file:
      - .env
      - sandol_amqp/.env.amqp
    ports:
      - "8081:8081"
    networks:
      - sandol-network
    depends_on:
      amqp:
        condition: service_healthy
      db:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/notice-notification/health" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    container_name: sandol-notice-notification-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sandol-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  amqp:
    container_name: amqp
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sandol-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sandol-network:
    driver: bridge

volumes:
  db_data:
